//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Packages/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""24f8a988-6af0-4b18-9bd9-488d0b146bc4"",
            ""actions"": [
                {
                    ""name"": ""ClickOnFigure"",
                    ""type"": ""Button"",
                    ""id"": ""021b77dd-54a1-4e6f-92f2-07cfeadf7537"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0a71690b-6805-4ea0-9dea-68cd3a538c71"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and mouse"",
                    ""action"": ""ClickOnFigure"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraSwitch"",
            ""id"": ""b95e792b-f1f4-42e1-98f0-7b3f154a7299"",
            ""actions"": [
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Value"",
                    ""id"": ""517f9083-42e0-45f8-9538-5c489549dccc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""d217adab-de79-4111-b3dd-11eb218f2727"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e5c1b385-6c10-499c-8505-4ea8823d1e02"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and mouse"",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1ab8b872-2f19-421b-a9e7-394973f3bd7d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and mouse"",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""c62b5413-e032-4813-b13a-03b368c276a9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d343a15b-9f10-4c21-aea5-b34bdeb7bbcd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and mouse"",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3b4e5a06-4b4e-429e-841e-a18896077b7a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and mouse"",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""FigureChoice"",
            ""id"": ""67691465-9bde-4817-98fa-f15dad5c7c1f"",
            ""actions"": [
                {
                    ""name"": ""SwapLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0596663a-28bc-49b3-8128-17ae193e0150"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapRight"",
                    ""type"": ""Button"",
                    ""id"": ""34cb6699-fa6b-43b4-a449-6bc00c46aabc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose"",
                    ""type"": ""Button"",
                    ""id"": ""1fe7530a-ff7e-4cc3-9f43-5a141e0ba6a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1b1c07b-fd80-402c-9261-37d20cf1c048"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Choose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e69c8aa-72c5-45d0-a2dd-0f30de31ed24"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4514c10-ce77-4f99-9ff5-130e57b1dd2b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8981d49c-bc24-40ab-88e9-0c3efa81b7db"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d9bf870-d3ef-4a2c-bed5-d951e4a9545f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and mouse"",
            ""bindingGroup"": ""Keyboard and mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ClickOnFigure = m_Player.FindAction("ClickOnFigure", throwIfNotFound: true);
        // CameraSwitch
        m_CameraSwitch = asset.FindActionMap("CameraSwitch", throwIfNotFound: true);
        m_CameraSwitch_SwitchCamera = m_CameraSwitch.FindAction("SwitchCamera", throwIfNotFound: true);
        // FigureChoice
        m_FigureChoice = asset.FindActionMap("FigureChoice", throwIfNotFound: true);
        m_FigureChoice_SwapLeft = m_FigureChoice.FindAction("SwapLeft", throwIfNotFound: true);
        m_FigureChoice_SwapRight = m_FigureChoice.FindAction("SwapRight", throwIfNotFound: true);
        m_FigureChoice_Choose = m_FigureChoice.FindAction("Choose", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInput.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CameraSwitch.enabled, "This will cause a leak and performance issues, PlayerInput.CameraSwitch.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FigureChoice.enabled, "This will cause a leak and performance issues, PlayerInput.FigureChoice.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ClickOnFigure;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ClickOnFigure => m_Wrapper.m_Player_ClickOnFigure;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ClickOnFigure.started += instance.OnClickOnFigure;
            @ClickOnFigure.performed += instance.OnClickOnFigure;
            @ClickOnFigure.canceled += instance.OnClickOnFigure;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ClickOnFigure.started -= instance.OnClickOnFigure;
            @ClickOnFigure.performed -= instance.OnClickOnFigure;
            @ClickOnFigure.canceled -= instance.OnClickOnFigure;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // CameraSwitch
    private readonly InputActionMap m_CameraSwitch;
    private List<ICameraSwitchActions> m_CameraSwitchActionsCallbackInterfaces = new List<ICameraSwitchActions>();
    private readonly InputAction m_CameraSwitch_SwitchCamera;
    public struct CameraSwitchActions
    {
        private @PlayerInput m_Wrapper;
        public CameraSwitchActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwitchCamera => m_Wrapper.m_CameraSwitch_SwitchCamera;
        public InputActionMap Get() { return m_Wrapper.m_CameraSwitch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraSwitchActions set) { return set.Get(); }
        public void AddCallbacks(ICameraSwitchActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraSwitchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraSwitchActionsCallbackInterfaces.Add(instance);
            @SwitchCamera.started += instance.OnSwitchCamera;
            @SwitchCamera.performed += instance.OnSwitchCamera;
            @SwitchCamera.canceled += instance.OnSwitchCamera;
        }

        private void UnregisterCallbacks(ICameraSwitchActions instance)
        {
            @SwitchCamera.started -= instance.OnSwitchCamera;
            @SwitchCamera.performed -= instance.OnSwitchCamera;
            @SwitchCamera.canceled -= instance.OnSwitchCamera;
        }

        public void RemoveCallbacks(ICameraSwitchActions instance)
        {
            if (m_Wrapper.m_CameraSwitchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraSwitchActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraSwitchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraSwitchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraSwitchActions @CameraSwitch => new CameraSwitchActions(this);

    // FigureChoice
    private readonly InputActionMap m_FigureChoice;
    private List<IFigureChoiceActions> m_FigureChoiceActionsCallbackInterfaces = new List<IFigureChoiceActions>();
    private readonly InputAction m_FigureChoice_SwapLeft;
    private readonly InputAction m_FigureChoice_SwapRight;
    private readonly InputAction m_FigureChoice_Choose;
    public struct FigureChoiceActions
    {
        private @PlayerInput m_Wrapper;
        public FigureChoiceActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwapLeft => m_Wrapper.m_FigureChoice_SwapLeft;
        public InputAction @SwapRight => m_Wrapper.m_FigureChoice_SwapRight;
        public InputAction @Choose => m_Wrapper.m_FigureChoice_Choose;
        public InputActionMap Get() { return m_Wrapper.m_FigureChoice; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FigureChoiceActions set) { return set.Get(); }
        public void AddCallbacks(IFigureChoiceActions instance)
        {
            if (instance == null || m_Wrapper.m_FigureChoiceActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FigureChoiceActionsCallbackInterfaces.Add(instance);
            @SwapLeft.started += instance.OnSwapLeft;
            @SwapLeft.performed += instance.OnSwapLeft;
            @SwapLeft.canceled += instance.OnSwapLeft;
            @SwapRight.started += instance.OnSwapRight;
            @SwapRight.performed += instance.OnSwapRight;
            @SwapRight.canceled += instance.OnSwapRight;
            @Choose.started += instance.OnChoose;
            @Choose.performed += instance.OnChoose;
            @Choose.canceled += instance.OnChoose;
        }

        private void UnregisterCallbacks(IFigureChoiceActions instance)
        {
            @SwapLeft.started -= instance.OnSwapLeft;
            @SwapLeft.performed -= instance.OnSwapLeft;
            @SwapLeft.canceled -= instance.OnSwapLeft;
            @SwapRight.started -= instance.OnSwapRight;
            @SwapRight.performed -= instance.OnSwapRight;
            @SwapRight.canceled -= instance.OnSwapRight;
            @Choose.started -= instance.OnChoose;
            @Choose.performed -= instance.OnChoose;
            @Choose.canceled -= instance.OnChoose;
        }

        public void RemoveCallbacks(IFigureChoiceActions instance)
        {
            if (m_Wrapper.m_FigureChoiceActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFigureChoiceActions instance)
        {
            foreach (var item in m_Wrapper.m_FigureChoiceActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FigureChoiceActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FigureChoiceActions @FigureChoice => new FigureChoiceActions(this);
    private int m_KeyboardandmouseSchemeIndex = -1;
    public InputControlScheme KeyboardandmouseScheme
    {
        get
        {
            if (m_KeyboardandmouseSchemeIndex == -1) m_KeyboardandmouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and mouse");
            return asset.controlSchemes[m_KeyboardandmouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnClickOnFigure(InputAction.CallbackContext context);
    }
    public interface ICameraSwitchActions
    {
        void OnSwitchCamera(InputAction.CallbackContext context);
    }
    public interface IFigureChoiceActions
    {
        void OnSwapLeft(InputAction.CallbackContext context);
        void OnSwapRight(InputAction.CallbackContext context);
        void OnChoose(InputAction.CallbackContext context);
    }
}
